apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stp-kn-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: stp-kn-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: git@github.com:ryan-highley/stp-kn-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
